# Configure a default setup of Home Assistant (frontend, API, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Prometheus integration for metrics
prometheus:
  namespace: hass

# Recorder settings for database
recorder:
  purge_keep_days: 30
  db_url: sqlite:///config/home-assistant_v2.db
